# Generated by Django 3.2 on 2023-04-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_auto_20230419_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
