# Generated by Django 3.2 on 2023-04-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0004_auto_20230420_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='storage',
        ),
        migrations.AddField(
            model_name='order',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='stock_app.box', verbose_name='Ячейка хранения'),
        ),
    ]
