# Generated by Django 3.2 on 2023-04-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0005_auto_20230421_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='storage',
        ),
        migrations.AddField(
            model_name='order',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='stock_app.box', verbose_name='Ячейка хранения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='stock_app.client', verbose_name='Клиент'),
        ),
    ]
