# Generated by Django 3.2 on 2023-04-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0006_alter_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qr_code',
        ),
    ]
