# Generated by Django 3.2 on 2023-04-23 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0006_order_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата оплаты'),
        ),
    ]
