# Generated by Django 3.2 on 2023-04-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0007_alter_order_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
