# Generated by Django 3.2 on 2023-04-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0008_auto_20230423_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_img',
            field=models.ImageField(default='', upload_to='', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
